function test_transport_block_size_determinate

I_mcs = 20;
pusch_tp = 1;
mcs_table_pusch = '64qam';
mcs_table_pusch_transform_precoding = '64qam';
N_scheduled_symbol = 7;
N_prb_dmrs = 12;
N_prb_overhead = 0;
n_prb = 20;
number_of_layers = 1;
most_recent_configured_tbs = 0;

[modulation_order, target_code_rate] = ulsch_modulation_order_and_target_code_rate(I_mcs, pusch_tp, mcs_table_pusch, mcs_table_pusch_transform_precoding);

transport_block_size = ulsch_transport_block_size_determinate(I_mcs, ...
                                                        modulation_order, ...
                                                        target_code_rate, ...
                                                        pusch_tp, ...
                                                        mcs_table_pusch, ...
                                                        mcs_table_pusch_transform_precoding, ...
                                                        N_scheduled_symbol, ...
                                                        N_prb_dmrs, ...
                                                        N_prb_overhead, ...
                                                        n_prb, ...
                                                        number_of_layers, ...
                                                        most_recent_configured_tbs);
                                                    
disp(transport_block_size);


end
